plugins {
	id 'java'
	id 'net.neoforged.moddev' version '2.0.147'
}

group = mod_group_id
version = mod_version

base {
	archivesName = mod_id
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
	version = project.neo_version

	parchment {
		minecraftVersion = project.minecraft_version
		mappingsVersion = project.parchment_version
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly files('../../minecraft/mods/Jade-1.21.1-NeoForge-15.10.6.jar')
	compileOnly files('../campfires/build/libs/campfires-1.0.0.jar')
}

tasks.named('processResources', ProcessResources).configure {
	var replaceProperties = [
			minecraft_version: minecraft_version,
			neo_version      : neo_version,
			mod_id           : mod_id,
			mod_name         : mod_name,
			mod_version      : mod_version,
			mod_author       : mod_author,
	]
	inputs.properties replaceProperties
	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
}
